// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ubkzwxonpiebyumxgxmm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVia3p3eG9ucGllYnl1bXhneG1tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNjA4ODMsImV4cCI6MjA3MTkzNjg4M30.1DEaUMaB2nkv1XHuyHtbEgp4DeuOkL3vq_nq9bHZaGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});